homeassistant:
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
  name: Home
  unit_system: metric
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  time_zone: !secret timezone
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  base_url: !secret http_url
  trusted_proxies: !secret trusted_proxy
  trusted_networks:
    - !secret trusted_subnet
  use_x_forwarded_for: true
  login_attempts_threshold: 3

updater:

# Frontend
frontend:
  javascript_version: latest
  themes: !include config/themes.yaml
config:
map:

# Base
automation: !include_dir_merge_list automations
sensor: !include_dir_merge_list config/sensors
script: !include_dir_merge_named scripts
scene: !include_dir_merge_list scenes

# Other
# alexa: !include config/alexa.yaml
homekit: !include config/homekit.yaml
weather: !include config/weather.yaml
binary_sensor: !include config/binary_sensors.yaml
climate: !include config/climate.yaml
cloud: !include config/cloud.yaml
counter: !include config/counter.yaml
device_tracker: !include config/device_trackers.yaml
group: !include config/groups.yaml
history: !include config/history.yaml
history_graph: !include config/history_graphs.yaml
hue: !include config/hue.yaml
ios: !include config/ios.yaml
light: !include config/lights.yaml
logbook: !include config/logbook.yaml
media_player: !include config/media_players.yaml
openuv: !include config/openuv.yaml
panel_custom: !include config/panel_custom.yaml
recorder: !include config/recorder.yaml
shell_command: !include config/shell_command.yaml
shopping_list:
sun:
switch: !include config/switches.yaml
zone: !include config/zones.yaml
input_number: !include config/input_number.yaml
input_boolean: !include config/input_boolean.yaml



