- platform: template
  sensors:
    house_average_temperature:
      friendly_name: "Average Temperature"
      value_template: '{{ ((float(states.sensor.kitchen_motion_sensor.attributes.temperature) + float(states.sensor.living_room_motion_sensor.attributes.temperature) + float(states.sensor.bedroom_motion_sensor.attributes.temperature)) / 3) | round(2) }}'
      unit_of_measurement: "°C"
      device_class: temperature
- platform: template
  sensors:
    house_average_light_level:
      friendly_name: "Average Light Level"
      value_template: '{{ ((float(states.sensor.kitchen_motion_sensor.attributes.lx) + float(states.sensor.living_room_motion_sensor.attributes.lx) + float(states.sensor.bedroom_motion_sensor.attributes.lx)) / 3) | round(2) }}'
      unit_of_measurement: "lux"
      device_class: illuminance