- platform: hue
  ip_address: !secret ip_hue_bridge_1
  token: !secret hue_user
- platform: template
  sensors:
    living_room_temperature:
      friendly_name: 'Living room temperature'
      value_template: '{{states.sensor.living_room_motion_sensor.attributes.temperature}}'
      unit_of_measurement: 째C
      device_class: temperature
    living_room_light_level:
      friendly_name: 'Living room light level'
      value_template: '{{states.sensor.living_room_motion_sensor.attributes.lx}}'
      unit_of_measurement: lux
      device_class: illuminance
    kitchen_temperature:
      friendly_name: 'Kitchen temperature'
      value_template: '{{states.sensor.kitchen_motion_sensor.attributes.temperature}}'
      unit_of_measurement: 째C
      device_class: temperature
    kitchen_light_level:
      friendly_name: 'Kitchen light level'
      value_template: '{{states.sensor.kitchen_motion_sensor.attributes.lx}}'
      unit_of_measurement: lux
      device_class: illuminance
    bedroom_temperature:
      friendly_name: 'Bedroom temperature'
      value_template: '{{states.sensor.bedroom_motion_sensor.attributes.temperature}}'
      unit_of_measurement: 째C
      device_class: temperature
    bedroom_light_level:
      friendly_name: 'Bedroom light level'
      value_template: '{{states.sensor.bedroom_motion_sensor.attributes.lx}}'
      unit_of_measurement: lux
      device_class: illuminance
    spare_room_temperature:
      friendly_name: 'Spare room temperature'
      value_template: '{{states.sensor.spare_room_motion_sensor.attributes.temperature}}'
      unit_of_measurement: 째C
      device_class: temperature
    spare_room_light_level:
      friendly_name: 'Spare room light level'
      value_template: '{{states.sensor.spare_room_motion_sensor.attributes.lx}}'
      unit_of_measurement: lux
      device_class: illuminance