- platform: speedtest
  minute:
    - 0
    - 15
    - 30
    - 45
  monitored_conditions:
    - ping
    - download
    - upload

- platform: dnsip
  hostname: !secret http_url
  resolver: 208.67.222.222
  scan_interval: 300
- platform: dnsip
  hostname: myip.opendns.com
  resolver: 208.67.222.222
  scan_interval: 300