- platform: template
  sensors:
    global_light_brightness:
      friendly_name: Global Light Brightness
      value_template: >
        {% set mapped_counter = ((((states('counter.global_fade_counter')|int,360) | min) / 360) * 255) | round(0) | int %}
        {% set early_value = (0 + mapped_counter) | int %}
        {% set late_value = (255 - mapped_counter)|int,5 | max | int %}
        {{ (255 - mapped_counter) | int }}
