- platform: template
  sensors:
    global_light_brightness:
      friendly_name: Global Light Brightness
      value_template: >
        {% set mapped_counter = ((((states('counter.global_fade_counter')|int,360) | min) / 360) * 255) | round(0) | int %}

        {%- if is_state('input_boolean.late_night', 'on') %}
          {% set min_value = 128 | int %}
        {%- else %}
          {% set min_value = 5 | int %}
        {%- endif %}

        {%- if now().hour | int >= 15 or now().hour | int < 3 %}
          {{ ((255 - mapped_counter)|int,min_value|int) | max | int }}
        {%- else %}
          {{ ((0 + mapped_counter)|int,min_value|int) | max | int }}
        {%- endif %}
