- platform: template
  sensors:
    global_light_brightness:
      friendly_name: Global Light Brightness
      value_template: >
        {% set mapped_counter = ((((states('counter.global_fade_counter')|int,360) | max) / 360) * 255) %}
        {{ mapped_counter | round(0) | int }}
