- platform: template
  sensors:
    global_light_brightness:
      friendly_name: Global Light Brightness
      value_template: >
        {%- set mapped_counter = (((states('counter.global_fade_counter'),'360' | max | int) / 360) * 255) %}
        {{ mapped_counter | rount(0) | int }}
