- platform: template
  sensors:
    global_light_brightness:
      friendly_name: Global Light Brightness
      value_template: >
        {% set mapped_counter = ((((states('counter.global_fade_counter')|int,360) | min) / 360) * 255) | round(0) | int %}
        {%- if (now().hour | int >= 15 or now().hour | int < 3) and is_state('input_boolean.late_night', 'on') %}
          {{ ((255 - mapped_counter)|int,128) | max | int }}
        {%- elif now().hour | int >= 15 or now().hour | int < 3 %}
          {{ ((255 - mapped_counter)|int,5) | max | int }}
        {%- elif is_state('input_boolean.late_night', 'on') %}
          {{ ((0 + mapped_counter)|int,128) | max | int }}
        {%- else %}
          {{ ((0 + mapped_counter)|int,5) | max | int }}
        {%- endif %}
