- platform: ping
  host: !secret ip_apollo
  count: 2
  scan_interval: 30
  name: Apollo
- platform: ping
  host: !secret ip_firewall
  count: 2
  scan_interval: 30
  name: Firewall
- platform: ping
  host: !secret ip_router
  count: 2
  scan_interval: 30
  name: Router
- platform: ping
  host: 8.8.8.8
  count: 2
  scan_interval: 30
  name: Google DNS