- platform: generic_thermostat
  name: Bedroom
  heater: switch.bedroom_heater
  target_sensor: sensor.bedroom_temperature
  min_temp: 15
  max_temp: 25
  ac_mode: false
  target_temp: 18
  min_cycle_duration:
    minutes: 1
  keep_alive:
    minutes: 1
  initial_operation_mode: "auto"
  away_temp: 16
  precision: 0.5
- platform: generic_thermostat
  name: Spare Room
  heater: switch.spare_room_heater
  target_sensor: sensor.spare_room_temperature
  min_temp: 15
  max_temp: 25
  ac_mode: false
  target_temp: 18
  min_cycle_duration:
    minutes: 1
  keep_alive:
    minutes: 1
  initial_operation_mode: "auto"
  away_temp: 16
  precision: 0.5