alexa:
  filter:
    include_entities:
      - light.living_room
      - light.kitchen
      - light.bedroom
      - light.spare_room
      - light.landing
      - switch.butt_plug_lamp
      - input_boolean.is_cooking
    exclude_domains:
      - alert
      - automation
      - cover
      - fan
      - group
      - input_boolean
      - light
      - lock
      - media_player
      - scene
      - script
      - switch
      - sensor
      - light
  entity_config:
    light.living_room:
      name: Living Room
      description: All living room lights
      display_categories: LIGHT
    light.kitchen:
      name: Kitchen
      description: All kitchen lights
      display_categories: LIGHT
    light.bedroom:
      name: Bedroom
      description: All bedroom lights
      display_categories: LIGHT
    light.spare_room:
      name: Spare Room
      description: All spare room lights
      display_categories: LIGHT
    light.landing:
      name: Landing
      description: All landing lights
      display_categories: LIGHT
    switch.butt_plug_lamp:
      name: Butt Plug Lamp
      description: The mighty butt plug lamp
      display_categories: LIGHT
    input_boolean.is_cooking:
      name: Cooking
      description: A flag to set if you are cooking
      display_categories: SWITCH
