cooking:
  name: Is Cooking
  initial: off
  icon: mdi:stove
late_night:
  name: Late Night
  initial: off
  icon: mdi:clock-outline
visitor_living_room:
  name: Visitor in Living Room
  initial: off
  icon: mdi:account-question
visitor_spare_room:
  name: Visitor in Spare Room
  initial: off
  icon: mdi:account-question
living_room_motion_lamp:
  name: Living Room Motion Lamps
  initial: off
  icon: mdi:run-fast
living_room_motion_ceiling:
  name: Living Room Motion Ceiling Lights
  initial: off
  icon: mdi:run-fast
bedroom_motion:
  name: Bedroom Motion Lights
  initial: off
  icon: mdi:run-fast
