target_bedroom_temperature:
  name: Target Bedroom Temperature
  initial: 18
  min: 15
  max: 25
  step: 0.5
  mode: slider
  unit_of_measurement: °C
target_spare_room_temperature:
  name: Target Spare Room Temperature
  initial: 18
  min: 15
  max: 25
  step: 0.5
  mode: slider
  unit_of_measurement: °C

kitchen_last_motion:
  name: Motion Last Detected In Kitchen
  initial: 0
  min: 0
  max: 2147000000
  step: 1
  mode: box
  unit_of_measurement: seconds