cooking:
  name: Is Cooking
  icon: mdi:stove
late_night:
  name: Late Night
  icon: mdi:clock-outline
visitor_living_room:
  name: Visitor in Living Room
  icon: mdi:account-question
visitor_spare_room:
  name: Visitor in Spare Room
  icon: mdi:account-question
living_room_motion_lamp:
  name: Living Room Motion Lamps
  icon: mdi:run-fast
living_room_motion_ceiling:
  name: Living Room Motion Ceiling Lights
  icon: mdi:run-fast
bedroom_motion:
  name: Bedroom Motion Lights
  icon: mdi:run-fast
