push:
  categories:
    - name: Spare Room Visitor
      identifier: 'visitor'
      actions:
        - identifier: 'STAYING_OVER'
          title: 'Staying Over'
          activationMode: 'foreground'
          authenticationRequired: no
          destructive: no
          behavior: 'default'
        - identifier: 'JUST_VISITING'
          title: 'Just Visiting'
          activationMode: 'background'
          authenticationRequired: no
          destructive: no
          behavior: 'default'
    - name: Alarm
      identifier: 'alarm'
      actions:
        - identifier: 'SOUND_ALARM'
          title: 'Sound Alarm'
          activationMode: 'background'
          authenticationRequired: no
          destructive: yes
          behavior: 'default'
        - identifier: 'SILENCE_ALARM'
          title: 'Silence Alarm'
          activationMode: 'background'
          authenticationRequired: no
          destructive: no
          behavior: 'textInput'
          textInputButtonTitle: 'Silencio!'
          textInputPlaceholder: 'Placeholder'
    - name: Rebel
      identifier: 'rebel'
      actions:
        - identifier: 'PRESS_YES'
          title: 'Yes'
          activationMode: 'background'
          authenticationRequired: no
          destructive: yes
          behavior: 'default'
        - identifier: 'PRESS_NO'
          title: 'No'
          activationMode: 'background'
          authenticationRequired: no
          destructive: no
          behavior: 'default'
