- platform: template
  lights:
    butt_plug_lamp:
      friendly_name: "Butt Plug Lamp"
      value_template: '{{ states.switch.butt_plug_lamp.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.butt_plug_lamp
      turn_off:
        service: switch.turn_off
        entity_id: switch.butt_plug_lamp
- platform: group
  name: Spare Room Ceiling
  entities:
    - light.spare_room_ceiling_1
    - light.spare_room_ceiling_2
- platform: group
  name: Home
  entities:
    - light.bedroom
    - light.landing
    - light.spare_room
    - light.living_room
    - light.kitchen
    - light.butt_plug_lamp

