# api_key: !secret open_uv_key
# sensors:
#   monitored_conditions:
#     - current_ozone_level
#     - current_uv_index
#     - current_uv_level
#     - max_uv_index
#     - safe_exposure_time_type_2
#     - safe_exposure_time_type_3
#     - safe_exposure_time_type_4
